//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Eid { get; set; }
        public string Foodname { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string OrderStatus { get; set; }
        public string EmpStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
    }
}
